//! Per-file quality filters and content normalization.

/// Why a file was excluded from the corpus. Each variant is a stats bucket.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Reject {
    NotUtf8,
    TooSmall,
    TooLarge,
    LongLines,
    Generated,
    Numeric,
    LowAlnum,
    Repetitive,
}

impl Reject {
    pub const ALL: &[Reject] = &[
        Reject::NotUtf8,
        Reject::TooSmall,
        Reject::TooLarge,
        Reject::LongLines,
        Reject::Generated,
        Reject::Numeric,
        Reject::LowAlnum,
        Reject::Repetitive,
    ];

    /// Position in `ALL`, for per-reason counters.
    pub fn index(self) -> usize {
        Reject::ALL.iter().position(|&r| r == self).unwrap()
    }

    pub fn name(self) -> &'static str {
        match self {
            Reject::NotUtf8 => "not_utf8",
            Reject::TooSmall => "too_small",
            Reject::TooLarge => "too_large",
            Reject::LongLines => "long_lines",
            Reject::Generated => "generated",
            Reject::Numeric => "numeric",
            Reject::LowAlnum => "low_alnum",
            Reject::Repetitive => "repetitive",
        }
    }
}

pub const MAX_FILE_BYTES: u64 = 512 * 1024;
const MIN_FILE_BYTES: usize = 16;
const LONG_LINE: usize = 1000;
const MAX_LINE_LEN: usize = 5000;
const MAX_LONG_LINE_FRACTION: f64 = 0.25;
const MAX_MEAN_LINE_LEN: usize = 150;
const BANNER_MAX_LINES: usize = 60;
const MAX_DIGIT_FRACTION: f64 = 0.30;
const MIN_ALNUM_FRACTION: f64 = 0.40;
const REPETITIVE_MIN_LINES: usize = 200;
const MIN_UNIQUE_LINE_FRACTION: f64 = 0.25;

const GENERATED_MARKERS: &[&str] = &[
    "@generated",
    "do not edit",
    "do not modify",
    "automatically generated",
    "auto-generated",
    "autogenerated",
    "generated by",
    "generated file",
    "this file was generated",
    "this file is generated",
    "code generated",
    "rust-bindgen",
];

/// Normalizes line endings and trailing whitespace, and strips a leading BOM.
/// Returns `None` if the bytes are not valid UTF-8.
pub fn normalize(bytes: &[u8]) -> Option<String> {
    let text = std::str::from_utf8(bytes).ok()?;
    let text = text.strip_prefix('\u{feff}').unwrap_or(text);
    let mut out = String::with_capacity(text.len());
    for line in text.split_inclusive('\n') {
        let line = line.strip_suffix('\n').unwrap_or(line);
        out.push_str(line.trim_end());
        out.push('\n');
    }
    // Remove blank lines at the end, keeping exactly one trailing newline.
    while out.ends_with("\n\n") {
        out.pop();
    }
    Some(out)
}

/// How a language writes comments, for reading the banner at the top of a file.
pub struct CommentStyle {
    /// Line comment openers.
    pub line: &'static [&'static str],
    /// Line comment openers that mark documentation; checked before `line`.
    pub doc_line: &'static [&'static str],
    /// Block comment opener and closer.
    pub block: Option<(&'static str, &'static str)>,
    /// Characters right after the block opener that make it a documentation comment.
    pub doc_block: &'static [char],
    /// Prefixes of a first line that is not code, such as a shebang.
    pub preamble: &'static [&'static str],
}

impl CommentStyle {
    /// Rust, and the C family with the same doc comment conventions.
    pub const C: CommentStyle = CommentStyle {
        line: &["//"],
        doc_line: &["///", "//!"],
        block: Some(("/*", "*/")),
        doc_block: &['*', '!'],
        preamble: &[],
    };
    /// Shell, Python, Perl, Ruby, Make and the other `#` languages.
    pub const HASH: CommentStyle = CommentStyle {
        line: &["#"],
        doc_line: &[],
        block: None,
        doc_block: &[],
        preamble: &["#!"],
    };
}

/// The banner of a file: the plain comments before the first line of code, lowercased.
/// Doc comments are skipped because they are prose about the code rather than a
/// statement about how the file was produced.
fn banner(content: &str, style: &CommentStyle) -> String {
    let mut out = String::new();
    // Inside a block comment; the flag says whether its contents should be scanned.
    let mut in_block: Option<bool> = None;
    for (i, line) in content.lines().take(BANNER_MAX_LINES).enumerate() {
        let t = line.trim_start();
        if let Some(scan) = in_block {
            if scan {
                out.push_str(t);
                out.push('\n');
            }
            if style.block.is_some_and(|(_, close)| t.contains(close)) {
                in_block = None;
            }
            continue;
        }
        if t.is_empty()
            || style.doc_line.iter().any(|p| t.starts_with(p))
            || (i == 0 && style.preamble.iter().any(|p| t.starts_with(p)))
        {
            continue;
        }
        if style.line.iter().any(|p| t.starts_with(p)) {
            out.push_str(t);
            out.push('\n');
            continue;
        }
        if let Some((open, close)) = style.block
            && let Some(rest) = t.strip_prefix(open)
        {
            let doc = rest.starts_with(style.doc_block);
            if !doc {
                out.push_str(t);
                out.push('\n');
            }
            if !rest.contains(close) {
                in_block = Some(!doc);
            }
            continue;
        }
        break;
    }
    out.make_ascii_lowercase();
    out
}

/// Returns the marker phrase that identifies a file as machine-generated, if any.
pub fn generated_marker_with(content: &str, style: &CommentStyle) -> Option<&'static str> {
    let banner = banner(content, style);
    if banner.is_empty() {
        return None;
    }
    GENERATED_MARKERS
        .iter()
        .copied()
        .find(|m| banner.contains(m))
}

/// Applies every quality filter to a normalized file whose comments look like `style`.
pub fn check_with(content: &str, style: &CommentStyle) -> Result<(), Reject> {
    if content.len() < MIN_FILE_BYTES {
        return Err(Reject::TooSmall);
    }
    if content.len() as u64 > MAX_FILE_BYTES {
        return Err(Reject::TooLarge);
    }

    if generated_marker_with(content, style).is_some() {
        return Err(Reject::Generated);
    }

    let mut lines = 0usize;
    let mut total_len = 0usize;
    let mut long_len = 0usize;
    let mut unique = std::collections::HashSet::new();
    for line in content.lines() {
        lines += 1;
        total_len += line.len();
        if line.len() > MAX_LINE_LEN {
            return Err(Reject::LongLines);
        }
        if line.len() > LONG_LINE {
            long_len += line.len();
        }
        if !line.trim().is_empty() {
            unique.insert(line.trim());
        }
    }
    if lines == 0 || total_len / lines > MAX_MEAN_LINE_LEN {
        return Err(Reject::LongLines);
    }
    if long_len as f64 / total_len as f64 > MAX_LONG_LINE_FRACTION {
        return Err(Reject::LongLines);
    }

    let mut non_ws = 0usize;
    let mut digits = 0usize;
    let mut alnum = 0usize;
    for c in content.chars() {
        if c.is_whitespace() {
            continue;
        }
        non_ws += 1;
        if c.is_ascii_digit() {
            digits += 1;
        }
        if c.is_alphanumeric() || c == '_' {
            alnum += 1;
        }
    }
    if non_ws == 0 {
        return Err(Reject::TooSmall);
    }
    if digits as f64 / non_ws as f64 > MAX_DIGIT_FRACTION {
        return Err(Reject::Numeric);
    }
    if (alnum as f64) / (non_ws as f64) < MIN_ALNUM_FRACTION {
        return Err(Reject::LowAlnum);
    }
    if lines >= REPETITIVE_MIN_LINES
        && (unique.len() as f64) / (lines as f64) < MIN_UNIQUE_LINE_FRACTION
    {
        return Err(Reject::Repetitive);
    }
    Ok(())
}

/// Path components that never contain code we want to train on.
pub fn excluded_path(path: &str) -> bool {
    path.split('/').any(|c| {
        c.starts_with('.')
            || matches!(
                c,
                "target" | "vendor" | "vendored" | "third_party" | "third-party" | "node_modules"
            )
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Applies every quality filter to a normalized Rust file.
    fn check(content: &str) -> Result<(), Reject> {
        check_with(content, &CommentStyle::C)
    }

    #[test]
    fn normalizes_endings() {
        assert_eq!(normalize(b"a  \r\nb\r\n\r\n\r\n").unwrap(), "a\nb\n");
        assert_eq!(normalize("\u{feff}x".as_bytes()).unwrap(), "x\n");
        assert!(normalize(&[0xff, 0xfe]).is_none());
    }

    #[test]
    fn rejects_generated() {
        let src = "/* automatically generated by rust-bindgen 0.60 */\npub const X: u32 = 1;\n";
        assert_eq!(check(src), Err(Reject::Generated));
        let src = "// This file is @generated by prost-build.\npub struct Msg {}\n";
        assert_eq!(check(src), Err(Reject::Generated));
        let src = "/*\n * Petstore\n *\n * Generated by: https://openapi-generator.tech\n */\n\nuse serde::Serialize;\n";
        assert_eq!(check(src), Err(Reject::Generated));
    }

    #[test]
    fn ignores_prose_mentions_of_generation() {
        let src = "//! Types were automatically generated from the JSON API description.\npub struct A;\n";
        assert_eq!(check(src), Ok(()));
        let src = "use std::fmt;\n\n/// Optional ID. If `None`, one is generated by the store.\npub struct Item;\n";
        assert_eq!(check(src), Ok(()));
        let src = "#![allow(clippy::all)] // clippy warns about code generated by #[pymethods]\npub struct A;\n";
        assert_eq!(check(src), Ok(()));
        let src = "/** Docs: do not edit the returned buffer. */\npub struct A;\n";
        assert_eq!(check(src), Ok(()));
    }

    #[test]
    fn hash_comment_banners() {
        let src =
            "#!/bin/sh\n# Generated by the protocol buffer compiler.  DO NOT EDIT!\nimport x\n";
        assert_eq!(check_with(src, &CommentStyle::HASH), Err(Reject::Generated));
        let src = "import os\n# this file is generated by the build\n";
        assert_eq!(check_with(src, &CommentStyle::HASH), Ok(()));
        // A Rust inner attribute is code, not a shebang, so the banner ends there.
        let src = "#![allow(dead_code)]\n// @generated\npub struct A;\n";
        assert_eq!(check(src), Ok(()));
    }

    #[test]
    fn long_lines() {
        let code: String = (0..200)
            .map(|i| format!("pub fn f{i}() -> u32 {{\n    {i}\n}}\n"))
            .collect();
        let blob = format!("const X: &str = \"{}\";\n", "ab".repeat(600));
        assert_eq!(check(&format!("{code}{blob}")), Ok(()));
        assert_eq!(
            check(&format!("{blob}{blob}{blob}pub fn g() {{}}\n")),
            Err(Reject::LongLines)
        );
        let huge = format!("const X: &str = \"{}\";\n", "ab".repeat(3000));
        assert_eq!(check(&format!("{code}{huge}")), Err(Reject::LongLines));
    }

    #[test]
    fn rejects_tables() {
        let mut src = String::from("pub const T: &[u8] = &[\n");
        for _ in 0..50 {
            src.push_str("    0x12, 0x34, 0x56, 0x78, 0x9a, 0xbc, 0xde, 0xf0,\n");
        }
        src.push_str("];\n");
        assert_eq!(check(&src), Err(Reject::Numeric));
    }

    #[test]
    fn accepts_code() {
        let src = "pub fn add(a: u32, b: u32) -> u32 {\n    a + b\n}\n";
        assert_eq!(check(src), Ok(()));
    }
}
